### ISSUE TITLE
Running Nosetests with sklearn 0.17 creates error in skutil.utils.tests.test_util.test_grid_search_fix

### ISSUE THREAD

**Issue by charlesdrotar** [tgsmith61591/skutil#20]
```bash
acbc327cf45b:skutil qwq594$ pip freeze | grep -i scikit-learn
scikit-learn==0.17.1
```

Running `nosetests` with sklearn 0.17.1 causes the following error:

```bash
======================================================================
ERROR: skutil.utils.tests.test_util.test_grid_search_fix
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/Users/qwq594/Library/Python/2.7/lib/python/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/qwq594/PycharmProjects/skutil/skutil/utils/tests/test_util.py", line 79, in test_grid_search_fix
    grid1.fit_predict(df, y)
  File "/Users/qwq594/PycharmProjects/skutil/skutil/utils/metaestimators.py", line 57, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
  File "/Users/qwq594/PycharmProjects/skutil/skutil/utils/fixes.py", line 339, in fit_predict
    return self.fit(X, y).predict(X)
  File "/Users/qwq594/PycharmProjects/skutil/skutil/utils/fixes.py", line 721, in fit
    return self._fit(X, y, ParameterGrid(self.param_grid))
  File "/Users/qwq594/PycharmProjects/skutil/skutil/utils/fixes.py", line 462, in _fit
    X, y = indexable(X, y)
NameError: global name 'indexable' is not defined
```

**Comment by tgsmith61591** [comment]
Fixed on master in 9eee444
